// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Kfilter_rcpp
Rcpp::List Kfilter_rcpp(arma::mat y_mat, arma::mat Phi, arma::vec mu0, arma::mat Cov0, arma::mat A, arma::mat Ca, double sigma2_eps);
RcppExport SEXP _temp_spat_pca3_Kfilter_rcpp(SEXP y_matSEXP, SEXP PhiSEXP, SEXP mu0SEXP, SEXP Cov0SEXP, SEXP ASEXP, SEXP CaSEXP, SEXP sigma2_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Cov0(Cov0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eps(sigma2_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Kfilter_rcpp(y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps));
    return rcpp_result_gen;
END_RCPP
}
// Ksmooth_rcpp
Rcpp::List Ksmooth_rcpp(arma::mat y_mat, arma::mat Phi, arma::vec mu0, arma::mat Cov0, arma::mat A, arma::mat Ca, double sigma2_eps);
RcppExport SEXP _temp_spat_pca3_Ksmooth_rcpp(SEXP y_matSEXP, SEXP PhiSEXP, SEXP mu0SEXP, SEXP Cov0SEXP, SEXP ASEXP, SEXP CaSEXP, SEXP sigma2_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Cov0(Cov0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eps(sigma2_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Ksmooth_rcpp(y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps));
    return rcpp_result_gen;
END_RCPP
}
// EM_fixedPhi_rcpp
Rcpp::List EM_fixedPhi_rcpp(arma::mat y_mat, arma::mat y_mat_new, arma::mat Phi, arma::vec mu0, arma::mat Cov0, arma::mat A, arma::mat Ca, double sigma2_eps, int itermax, double tol);
RcppExport SEXP _temp_spat_pca3_EM_fixedPhi_rcpp(SEXP y_matSEXP, SEXP y_mat_newSEXP, SEXP PhiSEXP, SEXP mu0SEXP, SEXP Cov0SEXP, SEXP ASEXP, SEXP CaSEXP, SEXP sigma2_epsSEXP, SEXP itermaxSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat_new(y_mat_newSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Cov0(Cov0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eps(sigma2_epsSEXP);
    Rcpp::traits::input_parameter< int >::type itermax(itermaxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(EM_fixedPhi_rcpp(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol));
    return rcpp_result_gen;
END_RCPP
}
// EM_nonfixedPhi_rcpp
Rcpp::List EM_nonfixedPhi_rcpp(arma::mat y_mat, arma::mat y_mat_new, arma::mat Phi, arma::vec mu0, arma::mat Cov0, arma::mat A, arma::mat Ca, double sigma2_eps, int itermax, double tol, double tau, arma::mat omega, double tol_m, double tol1, double tol2);
RcppExport SEXP _temp_spat_pca3_EM_nonfixedPhi_rcpp(SEXP y_matSEXP, SEXP y_mat_newSEXP, SEXP PhiSEXP, SEXP mu0SEXP, SEXP Cov0SEXP, SEXP ASEXP, SEXP CaSEXP, SEXP sigma2_epsSEXP, SEXP itermaxSEXP, SEXP tolSEXP, SEXP tauSEXP, SEXP omegaSEXP, SEXP tol_mSEXP, SEXP tol1SEXP, SEXP tol2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat_new(y_mat_newSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Cov0(Cov0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eps(sigma2_epsSEXP);
    Rcpp::traits::input_parameter< int >::type itermax(itermaxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type tol_m(tol_mSEXP);
    Rcpp::traits::input_parameter< double >::type tol1(tol1SEXP);
    Rcpp::traits::input_parameter< double >::type tol2(tol2SEXP);
    rcpp_result_gen = Rcpp::wrap(EM_nonfixedPhi_rcpp(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2));
    return rcpp_result_gen;
END_RCPP
}
// EM_nonfixedPhi_rcpp2
Rcpp::List EM_nonfixedPhi_rcpp2(arma::mat y_mat, arma::mat y_mat_new, arma::mat Phi, arma::vec mu0, arma::mat Cov0, arma::mat A, arma::mat Ca, double sigma2_eps, int itermax, double tol, double tau, arma::mat omega, double tol_m, double tol1, double tol2);
RcppExport SEXP _temp_spat_pca3_EM_nonfixedPhi_rcpp2(SEXP y_matSEXP, SEXP y_mat_newSEXP, SEXP PhiSEXP, SEXP mu0SEXP, SEXP Cov0SEXP, SEXP ASEXP, SEXP CaSEXP, SEXP sigma2_epsSEXP, SEXP itermaxSEXP, SEXP tolSEXP, SEXP tauSEXP, SEXP omegaSEXP, SEXP tol_mSEXP, SEXP tol1SEXP, SEXP tol2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y_mat(y_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_mat_new(y_mat_newSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Cov0(Cov0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ca(CaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eps(sigma2_epsSEXP);
    Rcpp::traits::input_parameter< int >::type itermax(itermaxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type tol_m(tol_mSEXP);
    Rcpp::traits::input_parameter< double >::type tol1(tol1SEXP);
    Rcpp::traits::input_parameter< double >::type tol2(tol2SEXP);
    rcpp_result_gen = Rcpp::wrap(EM_nonfixedPhi_rcpp2(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _temp_spat_pca3_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _temp_spat_pca3_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _temp_spat_pca3_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _temp_spat_pca3_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_temp_spat_pca3_Kfilter_rcpp", (DL_FUNC) &_temp_spat_pca3_Kfilter_rcpp, 7},
    {"_temp_spat_pca3_Ksmooth_rcpp", (DL_FUNC) &_temp_spat_pca3_Ksmooth_rcpp, 7},
    {"_temp_spat_pca3_EM_fixedPhi_rcpp", (DL_FUNC) &_temp_spat_pca3_EM_fixedPhi_rcpp, 10},
    {"_temp_spat_pca3_EM_nonfixedPhi_rcpp", (DL_FUNC) &_temp_spat_pca3_EM_nonfixedPhi_rcpp, 15},
    {"_temp_spat_pca3_EM_nonfixedPhi_rcpp2", (DL_FUNC) &_temp_spat_pca3_EM_nonfixedPhi_rcpp2, 15},
    {"_temp_spat_pca3_rcpparma_hello_world", (DL_FUNC) &_temp_spat_pca3_rcpparma_hello_world, 0},
    {"_temp_spat_pca3_rcpparma_outerproduct", (DL_FUNC) &_temp_spat_pca3_rcpparma_outerproduct, 1},
    {"_temp_spat_pca3_rcpparma_innerproduct", (DL_FUNC) &_temp_spat_pca3_rcpparma_innerproduct, 1},
    {"_temp_spat_pca3_rcpparma_bothproducts", (DL_FUNC) &_temp_spat_pca3_rcpparma_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_temp_spat_pca3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
