# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_new <- function(phi, Ceps_inv, yxi, S11, tau, omega) {
    .Call(`_temp_spat_pca3_f_new`, phi, Ceps_inv, yxi, S11, tau, omega)
}

f_new2 <- function(y_mat, phi, Ceps_inv, yxi, S11, tau, omega) {
    .Call(`_temp_spat_pca3_f_new2`, y_mat, phi, Ceps_inv, yxi, S11, tau, omega)
}

f_grad <- function(phi, Ceps_inv, yxi, S11, tau, omega) {
    .Call(`_temp_spat_pca3_f_grad`, phi, Ceps_inv, yxi, S11, tau, omega)
}

f_grad2 <- function(y_mat, phi, Ceps_inv, yxi, S11, tau, omega) {
    .Call(`_temp_spat_pca3_f_grad2`, y_mat, phi, Ceps_inv, yxi, S11, tau, omega)
}

line_search <- function(init, z2, learning_rate) {
    .Call(`_temp_spat_pca3_line_search`, init, z2, learning_rate)
}

find_phi <- function(init, Ceps_inv, yxi, S11, tau, omega, tol, tol1, tol2, verbose) {
    .Call(`_temp_spat_pca3_find_phi`, init, Ceps_inv, yxi, S11, tau, omega, tol, tol1, tol2, verbose)
}

find_phi2 <- function(y_mat, init, Ceps_inv, yxi, S11, tau, omega, tol, tol1, tol2, verbose) {
    .Call(`_temp_spat_pca3_find_phi2`, y_mat, init, Ceps_inv, yxi, S11, tau, omega, tol, tol1, tol2, verbose)
}

Kfilter_rcpp <- function(y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps) {
    .Call(`_temp_spat_pca3_Kfilter_rcpp`, y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps)
}

Ksmooth_rcpp <- function(y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps) {
    .Call(`_temp_spat_pca3_Ksmooth_rcpp`, y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps)
}

EM_fixedPhi_rcpp <- function(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol) {
    .Call(`_temp_spat_pca3_EM_fixedPhi_rcpp`, y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol)
}

EM_nonfixedPhi_rcpp <- function(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2) {
    .Call(`_temp_spat_pca3_EM_nonfixedPhi_rcpp`, y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2)
}

EM_nonfixedPhi_rcpp2 <- function(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2) {
    .Call(`_temp_spat_pca3_EM_nonfixedPhi_rcpp2`, y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2)
}

rcpparma_hello_world <- function() {
    .Call(`_temp_spat_pca3_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_temp_spat_pca3_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_temp_spat_pca3_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_temp_spat_pca3_rcpparma_bothproducts`, x)
}

