# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kfilter_rcpp <- function(y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps) {
    .Call('_temp_spat_pca3_Kfilter_rcpp', PACKAGE = 'temp.spat.pca3', y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps)
}

Ksmooth_rcpp <- function(y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps) {
    .Call('_temp_spat_pca3_Ksmooth_rcpp', PACKAGE = 'temp.spat.pca3', y_mat, Phi, mu0, Cov0, A, Ca, sigma2_eps)
}

EM_fixedPhi_rcpp <- function(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol) {
    .Call('_temp_spat_pca3_EM_fixedPhi_rcpp', PACKAGE = 'temp.spat.pca3', y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol)
}

EM_nonfixedPhi_rcpp <- function(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2) {
    .Call('_temp_spat_pca3_EM_nonfixedPhi_rcpp', PACKAGE = 'temp.spat.pca3', y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2)
}

EM_nonfixedPhi_rcpp2 <- function(y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2) {
    .Call('_temp_spat_pca3_EM_nonfixedPhi_rcpp2', PACKAGE = 'temp.spat.pca3', y_mat, y_mat_new, Phi, mu0, Cov0, A, Ca, sigma2_eps, itermax, tol, tau, omega, tol_m, tol1, tol2)
}

